import groovy.xml.*

def writer = new StringWriter()
def html = new MarkupBuilder(writer)

html.html{
	head{
		title 'Simple Document generated by Groovy Markup Builder'
	}
	body(id:'main'){
		h1 'Building HTML the Groovy Way'
		p{
			mkp.yield 'Mixing text with '
			strong 'bold'
			mkp.yield ' elements.'
		}
		a href: 'more.html', 'Read more...'
	}
}

println writer